//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fan
    {
        public string ModelNumber { get; set; }
        public string Airflow { get; set; }
        public string PowerMax { get; set; }
        public string PowerMin { get; set; }
        public string VoltageMax { get; set; }
        public string VoltageMin { get; set; }
        public string SpeedMax { get; set; }
        public string SpeedMin { get; set; }
        public string NumberOfSpeeds { get; set; }
        public string SweepDiameter { get; set; }
        public string SpeedSound { get; set; }
        public string HeightMax { get; set; }
        public string HeightMin { get; set; }
    }
}
