//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class JooleDatabaseEntities : DbContext
    {
        public JooleDatabaseEntities()
            : base("name=JooleDatabaseEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Couch> Couches { get; set; }
        public virtual DbSet<Fan> Fans { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<TableSaw> TableSaws { get; set; }
        public virtual DbSet<Toaster> Toasters { get; set; }
        public virtual DbSet<TV> TVs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacumm> Vacumms { get; set; }
        public virtual DbSet<Workbench> Workbenches { get; set; }
    }
}
