//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JooleDatabaseEntities : DbContext
    {
        public JooleDatabaseEntities()
            : base("name=JooleDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Couches> Couches { get; set; }
        public virtual DbSet<Fans> Fans { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<TableSaws> TableSaws { get; set; }
        public virtual DbSet<Toasters> Toasters { get; set; }
        public virtual DbSet<TVs> TVs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacumms> Vacumms { get; set; }
        public virtual DbSet<Workbenches> Workbenches { get; set; }
    }
}
