//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ModelNumber { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Weight { get; set; }
        public string ModelYear { get; set; }
        public string Manufacturer { get; set; }
        public string ProductName { get; set; }
        public string UseType { get; set; }
        public string Application { get; set; }
        public string Accessories { get; set; }
    }
}
