//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        public string ModelNumber { get; set; }
        public string Material { get; set; }
        public string Dimension { get; set; }
        public string Style { get; set; }
    }
}
