//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSaws
    {
        public string ModelNumber { get; set; }
        public string Power { get; set; }
        public string Voltage { get; set; }
        public string Amperes { get; set; }
        public string Dimension { get; set; }
        public string Speed { get; set; }
    }
}
