//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV
    {
        public string ModelNumber { get; set; }
        public string Power { get; set; }
        public string Voltage { get; set; }
        public string ScreenSize { get; set; }
        public string Dimension { get; set; }
        public string Resolution { get; set; }
        public string InputTypes { get; set; }
        public string OutputTypes { get; set; }
    }
}
